### ISSUE TITLE
Address and Registers

### ISSUE THREAD

**Issue by crazy-logic** [adafruit/Adafruit_CircuitPython_NeoKey#12]
Is there any documentation that has a list of address and registers for the neokey 1x4 QT board. 

I'm looking to implement via node.js rather than python for integration reasons. I can use the i2c library but need to know the registers to read the key presses from and write the LED values to. 

I can look further into reverse engineering this, but i thought i would ask first. I know the address is 0x30 for the first board on the chain. 

I have read https://forums.adafruit.com/viewtopic.php?t=187033 

I have found https://learn.adafruit.com/adafruit-seesaw-atsamd09-breakout/reading-and-writing-data, So i assume it's 0x0E for the pixels and 0x10 for reading the keys back.... but that's as far as i've got. 

I think this is how i would update a pixels colour data? (or rather this is where i'm at with my understanding)

Wire.beginTransmission((uint8_t)0x30); // address
Wire.write((uint8_t)0x03); //module base register address
Wire.write((uint8_t)???); //module function register address
Wire.write((uint8_t *)???, ???); //data bytes
Wire.endTransmission();

Wire.beginTransmission((uint8_t)0x30); // address
Wire.write((uint8_t)0x03); //module base register address
Wire.write((uint8_t) 0x05); //module function register address
Wire.endTransmission();

Any help much appreciated.

**Comment by FoamyGuy** [comment]
I don't know of any documentation listing that information. But the python code that implements it is available and fairly straightforward. 

It looks to me like this device does not use the `0x10` keypad base, and instead uses the `0x01` GPIO base. 

NeoKey class from this library reads the keys here: https://github.com/adafruit/Adafruit_CircuitPython_NeoKey/blob/main/adafruit_neokey/neokey1x4.py#L82 which is done by issueing a `digital_read_bulk()` call to the parent class Seesaw which is implemented here: https://github.com/adafruit/Adafruit_CircuitPython_seesaw/blob/main/adafruit_seesaw/seesaw.py#L230-L245

For the neopixel LEDs NeoKey class is creating this neopixel interface in it's constructor which is a different parent class from the seesaw library, in order to turn the LEDs on and off it's writing to the registers here: https://github.com/adafruit/Adafruit_CircuitPython_seesaw/blob/main/adafruit_seesaw/neopixel.py#L106

**Comment by tannewt** [comment]
I think there are two sources for seesaw firmware. For newer attiny boards there is https://github.com/adafruit/Adafruit_seesawPeripheral/tree/main/examples and for older samd boards there is https://github.com/adafruit/seesaw/tree/master/boards/NeoKey4_QT.
