### ISSUE TITLE
Wrong NeoPixel bytes

### ISSUE THREAD

**Issue by dastels** [adafruit/Adafruit_CircuitPython_NeoKey#7]
adafruit_seesaw.neopixel.NeoPixel defaults its byte oprder to GRBW.

adafruit_neokey.neokey1x4.NeoKey1x4 lets it do that when it should be setting an order of GRB in the NeoPixel constructor call to match the pixels on the neokey1x4 board.

**Comment by caternuson** [comment]
It looks like this PR:
https://github.com/adafruit/Adafruit_CircuitPython_seesaw/pull/102
fixed things, but changed behavior to break things elsewhere. Similar issue here:
https://github.com/adafruit/Adafruit_CircuitPython_NeoTrellis/issues/18

The fix is simple (just specify pixel order). But may be worth fixing in main library. Opened new issue here:
https://github.com/adafruit/Adafruit_CircuitPython_seesaw/issues/103
